#!/bin/bash

echo ""
echo "Welcome to the MySQL Helper Installer"
echo ""

VERSION=$(curl -Ls https://hnhdigital-os.github.io/mysql-helper/latest)

sudo curl -o /usr/local/bin/mysql-helper "https://hnhdigital-os.github.io/mysql-helper/download/${VERSION}/mysql-helper" && sudo chmod 755 /usr/local/bin/mysql-helper

echo ""
echo "Installation complete."
echo ""
